-- Migration script to update schema from category text to category_id

-- 1. Create temporary table to store existing products
create table if not exists public.products_temp (
  like public.products including all
);

-- 2. Copy existing data to temporary table
insert into public.products_temp
select * from public.products;

-- 3. Drop existing products table
drop table if exists public.products;

-- 4. Create new products table with category_id
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  category_id bigint references public.categories(id) on delete set null,
  brand text,
  quantity integer default 0 check (quantity >= 0),
  unit text default 'pcs' check (unit in ('pcs', 'kg', 'litre', 'box', 'pack')),
  price numeric(10, 2) not null check (price >= 0),
  discount numeric(5, 2) default 0.00 check (discount >= 0 and discount <= 100),
  expiry_date date,
  min_stock_level integer default 10,
  reorder_quantity integer default 20,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- 5. Migrate data from temporary table to new products table
insert into public.products (
  id, name, description, brand, quantity, unit, price, discount, expiry_date, created_at, updated_at,
  category_id, min_stock_level, reorder_quantity
)
select 
  p.id,
  p.name,
  p.description,
  p.brand,
  p.quantity,
  p.unit,
  p.price,
  p.discount,
  p.expiry_date,
  p.created_at,
  p.updated_at,
  c.id as category_id,
  10 as min_stock_level,
  20 as reorder_quantity
from public.products_temp p
left join public.categories c on c.name = p.category;

-- 6. Drop temporary table
drop table if exists public.products_temp;

-- 7. Update category totals for existing products
update public.categories c
set total_products = (
  select count(*) from public.products p where p.category_id = c.id
),
total_quantity = (
  select coalesce(sum(quantity), 0) from public.products p where p.category_id = c.id
); 